name: Python unit-tests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -e .[test]
        pip install mock coverage pytest
    - name: Test
      run: |
        DFLOW_HOST=${{ secrets.DFLOW_HOST }}
        DFLOW_K8S_API_SERVER=${{ secrets.DFLOW_K8S_API_SERVER }}
        DFLOW_S3_REPO_KEY=${{ secrets.DFLOW_S3_REPO_KEY }}
        DFLOW_S3_STORAGE_CLIENT=${{ secrets.DFLOW_S3_STORAGE_CLIENT }}
        BOHRIUM_USERNAME=${{ secrets.BOHRIUM_USERNAME }}
        BOHRIUM_PASSWORD=${{ secrets.BOHRIUM_PASSWORD }}
        BOHRIUM_PROJECT_ID=${{ secrets.BOHRIUM_PROJECT_ID }}
        cd tests 
        SKIP_UT_WITH_DFLOW=0 
        DFLOW_DEBUG=1 
        coverage run -m unittest -v -f 
        coverage report
    - uses: codecov/codecov-action@v3
